name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for tests
        run: docker build -t ashishkatkade/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true ashishkatkade/react-test npm test

      - name: Build Docker images
        run: |
          docker build -t ashishkatkade/multi-client ./client
          docker build -t ashishkatkade/multi-nginx ./nginx
          docker build -t ashishkatkade/multi-server ./server
          docker build -t ashishkatkade/multi-worker ./worker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push ashishkatkade/multi-client
          docker push ashishkatkade/multi-nginx
          docker push ashishkatkade/multi-server
          docker push ashishkatkade/multi-worker

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-north-1

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r deploy.zip .
          aws s3 cp deploy.zip s3://elasticbeanstalk-eu-north-1-590183798187/docker-multi/deploy.zip
          aws elasticbeanstalk create-application-version --application-name multi-docker --version-label $GITHUB_SHA --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-590183798187",S3Key="docker-multi/deploy.zip"
          aws elasticbeanstalk update-environment --environment-name Multi-docker-env --version-label $GITHUB_SHA

